/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
@StyleSheet
public class OboApplicationInitialPage extends javax.swing.JPanel {

    /**
     * Creates new form BuildingPermitInitialPage
     */
    public OboApplicationInitialPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xRadio4 = new com.rameses.rcp.control.XRadio();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xRadio3 = new com.rameses.rcp.control.XRadio();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xFileBrowser1 = new com.rameses.rcp.control.XFileBrowser();
        jLabel1 = new javax.swing.JLabel();

        xFormPanel1.setCaptionWidth(160);

        xRadio1.setCaption("From");
        xRadio1.setName("source"); // NOI18N
        xRadio1.setOptionValue("web");
        xRadio1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xRadio1.setShowCaption(false);
        xRadio1.setText("Download from web (via Filipizen)");
        xRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio1ActionPerformed(evt);
            }
        });
        xFormPanel1.add(xRadio1);

        xTextField1.setCaption("Enter Tracking No");
        xTextField1.setDepends(new String[] {"source"});
        xTextField1.setName("trackingno"); // NOI18N
        xTextField1.setVisibleWhen("#{ source == 'web' }");
        xTextField1.setCaptionWidth(150);
        xTextField1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 20));
        xTextField1.setRequired(true);
        xFormPanel1.add(xTextField1);

        xRadio4.setCaption("");
        xRadio4.setName("source"); // NOI18N
        xRadio4.setOptionValue("capture");
        xRadio4.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xRadio4.setShowCaption(false);
        xRadio4.setText("Manual Capture");
        xFormPanel1.add(xRadio4);

        xComboBox1.setCaption("Txn Mode");
        xComboBox1.setDepends(new String[] {"source"});
        xComboBox1.setItems("txnModes");
        xComboBox1.setName("txnmode"); // NOI18N
        xComboBox1.setVisibleWhen("#{ source == 'capture' }");
        xComboBox1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xComboBox2.setCaption("Workflow State");
        xComboBox2.setDepends(new String[] {"source", "txnmode"});
        xComboBox2.setItems("taskStates");
        xComboBox2.setName("taskstate"); // NOI18N
        xComboBox2.setVisibleWhen("#{ source == 'capture' && txnmode == 'CAPTURE'  }");
        xComboBox2.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xComboBox2.setRequired(true);
        xFormPanel1.add(xComboBox2);

        xRadio3.setCaption("");
        xRadio3.setName("source"); // NOI18N
        xRadio3.setOptionValue("file");
        xRadio3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xRadio3.setEnabled(false);
        xRadio3.setShowCaption(false);
        xRadio3.setText("File");
        xFormPanel1.add(xRadio3);

        xPanel1.setCaption("Select Filename");
        xPanel1.setDepends(new String[] {"source"});
        xPanel1.setVisibleWhen("#{ source == 'file' }");
        xPanel1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xPanel1.setPreferredSize(new java.awt.Dimension(0, 30));
        xPanel1.setLayout(new java.awt.BorderLayout());

        xFileBrowser1.setCaption("Select File name");
        xFileBrowser1.setEditable(true);
        xFileBrowser1.setName("filename"); // NOI18N
        xFileBrowser1.setVisibleWhen("");
        xFileBrowser1.setCaptionWidth(150);
        xFileBrowser1.setCellPadding(new java.awt.Insets(0, 30, 0, 0));
        xFileBrowser1.setPreferredSize(new java.awt.Dimension(0, 20));
        xPanel1.add(xFileBrowser1, java.awt.BorderLayout.CENTER);

        xFormPanel1.add(xPanel1);

        jLabel1.setText("Select an option and click Next to continue");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XFileBrowser xFileBrowser1;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio3;
    private com.rameses.rcp.control.XRadio xRadio4;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
}
