/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author elmonazareno
 */
@Template(CrudFormPage.class)
public class OboRequirementTypePage extends javax.swing.JPanel {

    /**
     * Creates new form OboRequirementTypePage
     */
    public OboRequirementTypePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xComboBox4 = new com.rameses.rcp.control.XComboBox();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox3 = new com.rameses.rcp.control.XComboBox();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();

        xFormPanel1.setCaption("General Info");
        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setPadding(new java.awt.Insets(25, 15, 15, 20));
        xTitledBorder1.setTitle("General Info");
        xFormPanel1.setBorder(xTitledBorder1);
        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(150);

        xTextField1.setCaption("Code");
        xTextField1.setDisableWhen("#{ mode != 'create' }");
        xTextField1.setName("entity.objid"); // NOI18N
        xTextField1.setRequired(true);
        xTextField1.setSpaceChar('_');
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Title");
        xTextField2.setName("entity.title"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField2.setRequired(true);
        xFormPanel1.add(xTextField2);

        xComboBox2.setCaption("Type");
        xComboBox2.setItems("types");
        xComboBox2.setName("entity.type"); // NOI18N
        xComboBox2.setPreferredSize(new java.awt.Dimension(150, 22));
        xFormPanel1.add(xComboBox2);

        xLookupField1.setCaption("Org");
        xLookupField1.setDepends(new String[] {"entity.type"});
        xLookupField1.setExpression("#{ entity.org.name }");
        xLookupField1.setHandler("org:lookup");
        xLookupField1.setName("entity.org"); // NOI18N
        xLookupField1.setVisibleWhen("#{ entity.type == 'WORKFLOW' }");
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLookupField1);

        xComboBox4.setCaption("Process Name");
        xComboBox4.setItems("processNames");
        xComboBox4.setName("entity.processname"); // NOI18N
        xComboBox4.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox4.setRequired(true);
        xFormPanel1.add(xComboBox4);

        xComboBox1.setCaption("Activation State");
        xComboBox1.setDepends(new String[] {"entity.processname"});
        xComboBox1.setExpression("#{ item.title }");
        xComboBox1.setItemKey("name");
        xComboBox1.setItems("workflowStates");
        xComboBox1.setName("entity.activationstate"); // NOI18N
        xComboBox1.setDynamic(true);
        xComboBox1.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox1.setRequired(true);
        xFormPanel1.add(xComboBox1);

        xComboBox3.setCaption("Validation State");
        xComboBox3.setDepends(new String[] {"entity.processname"});
        xComboBox3.setExpression("#{ item.title }");
        xComboBox3.setItemKey("name");
        xComboBox3.setItems("workflowStates");
        xComboBox3.setName("entity.validationstate"); // NOI18N
        xComboBox3.setDynamic(true);
        xComboBox3.setPreferredSize(new java.awt.Dimension(150, 22));
        xComboBox3.setRequired(true);
        xFormPanel1.add(xComboBox3);

        xIntegerField1.setCaption("Sort Index");
        xIntegerField1.setName("entity.sortindex"); // NOI18N
        xIntegerField1.setPreferredSize(new java.awt.Dimension(50, 20));
        xIntegerField1.setRequired(true);
        xFormPanel1.add(xIntegerField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XComboBox xComboBox3;
    private com.rameses.rcp.control.XComboBox xComboBox4;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
