/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.occupancy.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class OccupancyApplicationEditPage extends javax.swing.JPanel {

    /**
     * Creates new form OccupancyApplicationCapturePage
     */
    public OccupancyApplicationEditPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel21 = new com.rameses.rcp.control.XLabel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel6 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel2 = new com.rameses.rcp.control.XLabel();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel3 = new com.rameses.rcp.control.XFormPanel();
        xLabel11 = new com.rameses.rcp.control.XLabel();
        xLabel10 = new com.rameses.rcp.control.XLabel();
        xLabel32 = new com.rameses.rcp.control.XLabel();
        xLabel36 = new com.rameses.rcp.control.XLabel();
        xLabel37 = new com.rameses.rcp.control.XLabel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xLabel13 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel34 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        xFormPanel4 = new com.rameses.rcp.control.XFormPanel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField5 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField6 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField7 = new com.rameses.rcp.control.XDecimalField();
        xLabel35 = new com.rameses.rcp.control.XLabel();
        xDateField6 = new com.rameses.rcp.control.XDateField();
        xDateField7 = new com.rameses.rcp.control.XDateField();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel22 = new com.rameses.rcp.control.XLabel();
        xTextField6 = new com.rameses.rcp.control.XTextField();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xDateField5 = new com.rameses.rcp.control.XDateField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xTextField4 = new com.rameses.rcp.control.XTextField();
        xTextField5 = new com.rameses.rcp.control.XTextField();
        xLabel19 = new com.rameses.rcp.control.XLabel();
        xLabel55 = new com.rameses.rcp.control.XLabel();
        xLabel56 = new com.rameses.rcp.control.XLabel();
        xLookupField3 = new com.rameses.rcp.control.XLookupField();
        xCheckBox1 = new com.rameses.rcp.control.XCheckBox();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        xButton2 = new com.rameses.rcp.control.XButton();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xTextField7 = new com.rameses.rcp.control.XTextField();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        xDateField4 = new com.rameses.rcp.control.XDateField();
        xTextField9 = new com.rameses.rcp.control.XTextField();
        xDateField8 = new com.rameses.rcp.control.XDateField();
        xDecimalField8 = new com.rameses.rcp.control.XDecimalField();

        xFormPanel1.setCaptionWidth(190);
        xFormPanel1.setPreferredSize(new java.awt.Dimension(200, 300));

        xLabel21.setExpression("Project Info");
        xLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xLabel21.setShowCaption(false);
        xFormPanel1.add(xLabel21);

        xLabel9.setCaption("Bldg Permit No");
        xLabel9.setExpression("<html>#{entity.bldgpermit.controlno}</html>");
        xLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel9);

        xLabel8.setCaption("Project Title");
        xLabel8.setExpression("<html>#{entity.bldgpermit.title}</html>");
        xLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel8);

        xLabel7.setCaption("Project Description");
        xLabel7.setExpression("<html>#{entity.bldgpermit.description}</html>");
        xLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 40));
        xFormPanel1.add(xLabel7);

        xLabel6.setCaption("Location");
        xLabel6.setExpression("<html>#{entity.bldgpermit.location.text}</html>");
        xLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel6.setPreferredSize(new java.awt.Dimension(0, 40));
        xFormPanel1.add(xLabel6);

        xLabel4.setCaption("Applicant");
        xLabel4.setExpression("#{entity.bldgpermit.applicant.name}");
        xLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel4);

        xLabel2.setCaption("Occupancy Type");
        xLabel2.setExpression("<html>#{entity.occupancytype.group.objid} ( #{entity.occupancytype.division.objid} ) - #{entity.occupancytype.title }</html>");
        xLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel2.setPreferredSize(new java.awt.Dimension(0, 60));
        xFormPanel1.add(xLabel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        xFormPanel3.setCaptionWidth(190);
        xFormPanel3.setPreferredSize(new java.awt.Dimension(400, 199));

        xLabel11.setCaption("");
        xLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel11.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel11.setText("<html><b>Planned</b></html>");
        xFormPanel3.add(xLabel11);

        xLabel10.setCaption("No. of Units");
        xLabel10.setExpression("#{entity.bldgpermit.numunits}");
        xLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel10.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel10);

        xLabel32.setCaption("No. of Storeys");
        xLabel32.setExpression("#{entity.bldgpermit.numfloors}");
        xLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel32.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel32);

        xLabel36.setCaption("Total Floor Area");
        xLabel36.setExpression("#{entity.bldgpermit.totalfloorarea}");
        xLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel36.setNumberFormat("##0.00");
        xLabel36.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel36);

        xLabel37.setCaption("Bldg Height");
        xLabel37.setExpression("#{entity.bldgpermit.height}");
        xLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel37.setNumberFormat("##0.00");
        xLabel37.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel37);

        xLabel1.setCaption("");
        xLabel1.setExpression("Total Material Cost");
        xLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel1.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLabel1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel1);

        xLabel5.setCaption("");
        xLabel5.setExpression("Total Direct Labor Cost");
        xLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel5);

        xLabel13.setCaption("");
        xLabel13.setExpression("Total Equipment Cost");
        xLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel13.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel13);

        xLabel14.setCaption("");
        xLabel14.setExpression("Total Other Cost");
        xLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel14);

        xLabel34.setCaption("Est. Project Cost");
        xLabel34.setExpression("#{entity.bldgpermit.projectcost}");
        xLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel34.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel34.setNumberFormat("#,##0.00");
        xLabel34.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel34);

        xLabel15.setCaption("Start Construction Date");
        xLabel15.setExpression("#{entity.bldgpermit.dtproposedconstruction}");
        xLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel15.setDateFormat("yyyy MMM dd");
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel15);

        xLabel16.setCaption("Completion Date");
        xLabel16.setExpression("#{entity.bldgpermit.dtexpectedcompletion}");
        xLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel16.setDateFormat("yyyy MMM dd");
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel3.add(xLabel16);

        jPanel1.add(xFormPanel3, java.awt.BorderLayout.CENTER);

        xFormPanel4.setCaptionWidth(190);
        xFormPanel4.setShowCaption(false);

        xLabel12.setCaption("");
        xLabel12.setExpression("<html><b>Actual</b></html>");
        xLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel12.setShowCaption(false);
        xFormPanel4.add(xLabel12);

        xIntegerField1.setCaption("Acta");
        xIntegerField1.setName("entity.actualnumunits"); // NOI18N
        xIntegerField1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xIntegerField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xIntegerField1.setShowCaption(false);
        xFormPanel4.add(xIntegerField1);

        xIntegerField2.setCaption("Acta");
        xIntegerField2.setName("entity.actualnumfloors"); // NOI18N
        xIntegerField2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xIntegerField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xIntegerField2.setShowCaption(false);
        xFormPanel4.add(xIntegerField2);

        xDecimalField1.setName("entity.actualtotalfloorarea"); // NOI18N
        xDecimalField1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField1.setShowCaption(false);
        xFormPanel4.add(xDecimalField1);

        xDecimalField2.setName("entity.actualheight"); // NOI18N
        xDecimalField2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField2.setShowCaption(false);
        xFormPanel4.add(xDecimalField2);

        xDecimalField4.setName("entity.totalmaterialcost"); // NOI18N
        xDecimalField4.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xDecimalField4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField4.setShowCaption(false);
        xFormPanel4.add(xDecimalField4);

        xDecimalField5.setName("entity.totaldirectlaborcost"); // NOI18N
        xDecimalField5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField5.setShowCaption(false);
        xFormPanel4.add(xDecimalField5);

        xDecimalField6.setName("entity.totalequipmentcost"); // NOI18N
        xDecimalField6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField6.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField6.setShowCaption(false);
        xFormPanel4.add(xDecimalField6);

        xDecimalField7.setName("entity.totalothercost"); // NOI18N
        xDecimalField7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xDecimalField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xDecimalField7.setShowCaption(false);
        xFormPanel4.add(xDecimalField7);

        xLabel35.setCaption("");
        xLabel35.setExpression("#{entity.actualprojectcost}");
        xLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        xLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel35.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLabel35.setNumberFormat("#,##0.00");
        xLabel35.setPreferredSize(new java.awt.Dimension(0, 20));
        xLabel35.setShowCaption(false);
        xFormPanel4.add(xLabel35);

        xDateField6.setCaption("Date Issued");
        xDateField6.setName("entity.dtactualstarted"); // NOI18N
        xDateField6.setPreferredSize(new java.awt.Dimension(180, 20));
        xDateField6.setShowCaption(false);
        xFormPanel4.add(xDateField6);

        xDateField7.setCaption("Date Issued");
        xDateField7.setName("entity.dtactualcompleted"); // NOI18N
        xDateField7.setPreferredSize(new java.awt.Dimension(180, 20));
        xDateField7.setShowCaption(false);
        xFormPanel4.add(xDateField7);

        jPanel1.add(xFormPanel4, java.awt.BorderLayout.EAST);

        xFormPanel2.setCaptionWidth(160);

        xLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xLabel22.setShowCaption(false);
        xLabel22.setText("Application Info");
        xFormPanel2.add(xLabel22);

        xTextField6.setCaption("App No");
        xTextField6.setName("entity.appno"); // NOI18N
        xTextField6.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xTextField6);

        xLabel3.setCaption("");
        xLabel3.setExpression("Leave this blank to auto generate the app no");
        xFormPanel2.add(xLabel3);

        xComboBox1.setCaption("Txn Type");
        xComboBox1.setItems("txnTypes");
        xComboBox1.setName("entity.txntype"); // NOI18N
        xComboBox1.setRequired(true);
        xFormPanel2.add(xComboBox1);

        xComboBox2.setCaption("App Type");
        xComboBox2.setItems("appTypes");
        xComboBox2.setName("entity.apptype"); // NOI18N
        xComboBox2.setRequired(true);
        xFormPanel2.add(xComboBox2);

        xDateField5.setCaption("App Date");
        xDateField5.setName("entity.appdate"); // NOI18N
        xDateField5.setPreferredSize(new java.awt.Dimension(120, 20));
        xDateField5.setRequired(true);
        xFormPanel2.add(xDateField5);

        xTextField3.setCaption("Contact Name");
        xTextField3.setName("entity.contact.name"); // NOI18N
        xTextField3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xTextField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField3.setRequired(true);
        xFormPanel2.add(xTextField3);

        xTextField4.setCaption("Contact Email");
        xTextField4.setName("entity.contact.email"); // NOI18N
        xTextField4.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField4.setRequired(true);
        xTextField4.setTextCase(com.rameses.rcp.constant.TextCase.NONE);
        xFormPanel2.add(xTextField4);

        xTextField5.setCaption("Contact Mobile No");
        xTextField5.setName("entity.contact.mobileno"); // NOI18N
        xTextField5.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField5.setRequired(true);
        xFormPanel2.add(xTextField5);

        xLabel19.setExpression("Zone Classification");
        xLabel19.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xLabel19.setShowCaption(false);
        xFormPanel2.add(xLabel19);

        xLabel55.setCaption("Zone classification");
        xLabel55.setExpression("#{entity.bldgpermit.zoneclass.objid} - #{entity.bldgpermit.zoneclass.title}");
        xLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel55.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel55);

        xLabel56.setCaption("Zone ");
        xLabel56.setExpression("#{entity.bldgpermit.zone}");
        xLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel56.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel56);

        xLookupField3.setCaption("Project Supervisor");
        xLookupField3.setExpression("#{ entity.supervisor?.objid == null ? '' : entity.supervisor.lastname + ', ' + entity.supervisor.firstname + '/'+ entity.supervisor.profession + '-PRC No:' + entity.supervisor.prc.idno }");
        xLookupField3.setHandler("obo_professional:lookup");
        xLookupField3.setName("entity.supervisor"); // NOI18N
        xLookupField3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLookupField3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLookupField3);

        xCheckBox1.setName("hascontractor"); // NOI18N
        xCheckBox1.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xCheckBox1.setShowCaption(false);
        xCheckBox1.setText("Has Contractor?");
        xFormPanel2.add(xCheckBox1);

        xPanel2.setCaption("Contractor");
        xPanel2.setDepends(new String[] {"hascontractor"});
        xPanel2.setVisibleWhen("#{ hascontractor == true }");
        xPanel2.setPreferredSize(new java.awt.Dimension(0, 29));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 2, 0);
        flowLayout1.setAlignOnBaseline(true);
        xPanel2.setLayout(flowLayout1);

        xLabel18.setCaption("Contractor");
        xLabel18.setExpression("#{ entity.contractor.name }");
        xLabel18.setName("entity.contractor"); // NOI18N
        xLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xLabel18.setPreferredSize(new java.awt.Dimension(250, 25));
        xPanel2.add(xLabel18);

        xButton2.setName("editContractor"); // NOI18N
        xButton2.setIconResource("images/toolbars/edit.png");
        xButton2.setImmediate(true);
        xButton2.setPreferredSize(new java.awt.Dimension(30, 29));
        xButton2.setTarget("");
        xPanel2.add(xButton2);

        xFormPanel2.add(xPanel2);

        xLabel17.setCaption("");
        xLabel17.setExpression("Occupancy Permit Info");
        xLabel17.setName("zonetitle"); // NOI18N
        xLabel17.setVisibleWhen("#{ entity.permitissued == true }");
        xLabel17.setCellPadding(new java.awt.Insets(10, 0, 0, 0));
        xLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        xLabel17.setShowCaption(false);
        xFormPanel2.add(xLabel17);

        xTextField7.setCaption("Permit No");
        xTextField7.setDepends(new String[] {"entity.permitissued"});
        xTextField7.setName("entity.permitno"); // NOI18N
        xTextField7.setVisibleWhen("#{ entity.permitissued == true }");
        xTextField7.setPreferredSize(new java.awt.Dimension(0, 20));
        xTextField7.setRequired(true);
        xFormPanel2.add(xTextField7);

        xDateField3.setCaption("Date Issued");
        xDateField3.setDepends(new String[] {"entity.permitissued"});
        xDateField3.setName("entity.permitdtissued"); // NOI18N
        xDateField3.setVisibleWhen("#{ entity.permitissued == true }");
        xDateField3.setPreferredSize(new java.awt.Dimension(180, 20));
        xDateField3.setRequired(true);
        xFormPanel2.add(xDateField3);

        xDateField4.setCaption("Permit Expiry Date");
        xDateField4.setDepends(new String[] {"entity.permitissued"});
        xDateField4.setName("entity.permitexpirydate"); // NOI18N
        xDateField4.setVisibleWhen("#{ entity.permitissued == true }");
        xDateField4.setPreferredSize(new java.awt.Dimension(180, 20));
        xDateField4.setRequired(true);
        xFormPanel2.add(xDateField4);

        xTextField9.setCaption("Payment Ref No");
        xTextField9.setName("entity.receiptno"); // NOI18N
        xTextField9.setVisibleWhen("#{ entity.permitissued == true }");
        xTextField9.setPreferredSize(new java.awt.Dimension(180, 20));
        xTextField9.setRequired(true);
        xFormPanel2.add(xTextField9);

        xDateField8.setCaption("Payment Date");
        xDateField8.setName("entity.receiptdate"); // NOI18N
        xDateField8.setVisibleWhen("#{ entity.permitissued == true }");
        xDateField8.setPreferredSize(new java.awt.Dimension(180, 20));
        xDateField8.setRequired(true);
        xFormPanel2.add(xDateField8);

        xDecimalField8.setCaption("Amount Paid");
        xDecimalField8.setName("entity.amtpaid"); // NOI18N
        xDecimalField8.setVisibleWhen("#{ entity.permitissued == true }");
        xFormPanel2.add(xDecimalField8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XCheckBox xCheckBox1;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDateField xDateField4;
    private com.rameses.rcp.control.XDateField xDateField5;
    private com.rameses.rcp.control.XDateField xDateField6;
    private com.rameses.rcp.control.XDateField xDateField7;
    private com.rameses.rcp.control.XDateField xDateField8;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XDecimalField xDecimalField5;
    private com.rameses.rcp.control.XDecimalField xDecimalField6;
    private com.rameses.rcp.control.XDecimalField xDecimalField7;
    private com.rameses.rcp.control.XDecimalField xDecimalField8;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XFormPanel xFormPanel3;
    private com.rameses.rcp.control.XFormPanel xFormPanel4;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XLabel xLabel10;
    private com.rameses.rcp.control.XLabel xLabel11;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel13;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel19;
    private com.rameses.rcp.control.XLabel xLabel2;
    private com.rameses.rcp.control.XLabel xLabel21;
    private com.rameses.rcp.control.XLabel xLabel22;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLabel xLabel32;
    private com.rameses.rcp.control.XLabel xLabel34;
    private com.rameses.rcp.control.XLabel xLabel35;
    private com.rameses.rcp.control.XLabel xLabel36;
    private com.rameses.rcp.control.XLabel xLabel37;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel55;
    private com.rameses.rcp.control.XLabel xLabel56;
    private com.rameses.rcp.control.XLabel xLabel6;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XLookupField xLookupField3;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XTextField xTextField3;
    private com.rameses.rcp.control.XTextField xTextField4;
    private com.rameses.rcp.control.XTextField xTextField5;
    private com.rameses.rcp.control.XTextField xTextField6;
    private com.rameses.rcp.control.XTextField xTextField7;
    private com.rameses.rcp.control.XTextField xTextField9;
    // End of variables declaration//GEN-END:variables
}
