/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.occupancy.views;

import com.rameses.rcp.ui.annotations.Template;
import com.rameses.seti2.views.CrudFormPage;

/**
 *
 * @author elmonazareno
 */
@Template(CrudFormPage.class)
public class OccupancyPermitDocPage extends javax.swing.JPanel {

    /**
     * Creates new form BuildingPermitAncillaryPage
     */
    public OccupancyPermitDocPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xTabbedPane1 = new com.rameses.rcp.control.XTabbedPane();
        xPanel2 = new com.rameses.rcp.control.XPanel();
        applicationInfoList1 = new com.rameses.gov.etracs.obo.components.ApplicationInfoList();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        applicationFeeList1 = new com.rameses.gov.etracs.obo.components.ApplicationFeeList();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xLabel8 = new com.rameses.rcp.control.XLabel();
        xLabel7 = new com.rameses.rcp.control.XLabel();
        xLabel4 = new com.rameses.rcp.control.XLabel();
        xLabel5 = new com.rameses.rcp.control.XLabel();
        xFormPanel2 = new com.rameses.rcp.control.XFormPanel();
        xLabel9 = new com.rameses.rcp.control.XLabel();
        xLabel12 = new com.rameses.rcp.control.XLabel();
        xLabel15 = new com.rameses.rcp.control.XLabel();
        xLabel16 = new com.rameses.rcp.control.XLabel();
        xLabel17 = new com.rameses.rcp.control.XLabel();
        xLabel14 = new com.rameses.rcp.control.XLabel();
        xLabel18 = new com.rameses.rcp.control.XLabel();
        xActionBar3 = new com.rameses.rcp.control.XActionBar();

        setPreferredSize(new java.awt.Dimension(809, 488));
        setLayout(new java.awt.BorderLayout());

        xPanel2.setVisibleWhen("#{ showInfos == true }");
        xPanel2.setLayout(new java.awt.BorderLayout());

        applicationInfoList1.setAppid("entity.appid");
        applicationInfoList1.setDoctypeid("entity.doctypeid");
        applicationInfoList1.setEditableWhen("#{ editable }");
        applicationInfoList1.setEntitySchemaName("occupancy_permit_info");
        applicationInfoList1.setParentid("entity.objid");
        applicationInfoList1.setSchemaName("vw_occupancy_permit_info");
        xPanel2.add(applicationInfoList1, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("Infos", xPanel2);

        xPanel1.setVisibleWhen("#{ showFees == true }");
        xPanel1.setLayout(new java.awt.BorderLayout());

        applicationFeeList1.setAppid("entity.appid");
        applicationFeeList1.setEditableWhen("#{ editable }");
        applicationFeeList1.setEntitySchemaName("occupancy_permit_fee");
        applicationFeeList1.setHandler("feeHandler");
        applicationFeeList1.setParentid("entity.objid");
        applicationFeeList1.setSchemaName("vw_occupancy_permit_fee");
        xPanel1.add(applicationFeeList1, java.awt.BorderLayout.CENTER);

        xTabbedPane1.addTab("Fees", xPanel1);

        add(xTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        com.rameses.rcp.control.border.XTitledBorder xTitledBorder1 = new com.rameses.rcp.control.border.XTitledBorder();
        xTitledBorder1.setTitle("General Info");
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), xTitledBorder1));
        jPanel1.setPreferredSize(new java.awt.Dimension(766, 220));

        xFormPanel1.setCaptionWidth(100);

        xLabel8.setCaption("Control No");
        xLabel8.setExpression("#{entity.controlno}");
        xLabel8.setVisibleWhen("#{ entity.controlid !=null }");
        xLabel8.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel8);

        xLabel7.setCaption("Date Issued");
        xLabel7.setExpression("#{entity.dtissued}");
        xLabel7.setVisibleWhen("#{ entity.controlid !=null }");
        xLabel7.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel7);

        xLabel4.setCaption("Issued by");
        xLabel4.setExpression("#{entity.issuedby.name}");
        xLabel4.setVisibleWhen("#{ entity.controlid !=null }");
        xLabel4.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel4);

        xLabel5.setCaption("Expiry date");
        xLabel5.setExpression("#{entity.expirydate}");
        xLabel5.setVisibleWhen("#{ entity.controlid !=null }");
        xLabel5.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel5);

        xFormPanel2.setCaptionWidth(150);

        xLabel9.setCaption("Doc Type");
        xLabel9.setExpression("#{entity.doctype.title}");
        xLabel9.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel9);

        xLabel12.setCaption("App No");
        xLabel12.setExpression("#{entity.app.appno}");
        xLabel12.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel12);

        xLabel15.setCaption("Project Title");
        xLabel15.setExpression("#{entity.app.bldgpermit.title}");
        xLabel15.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel15);

        xLabel16.setCaption("Location");
        xLabel16.setExpression("#{entity.app.bldgpermit.location.text}");
        xLabel16.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel16);

        xLabel17.setCaption("Applicant");
        xLabel17.setExpression("#{entity.app.applicant.name}");
        xLabel17.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel17);

        xLabel14.setCaption("Occupancy Type");
        xLabel14.setExpression("#{entity.app.occupancytype.title}");
        xLabel14.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel14);

        xLabel18.setCaption("Actual Project Cost");
        xLabel18.setExpression("#{entity.app.actualprojectcost}");
        xLabel18.setNumberFormat("#,##0.00");
        xLabel18.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel2.add(xLabel18);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(xFormPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(xFormPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(xFormPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.CENTER);

        xActionBar3.setFormName("formName");
        xActionBar3.setName("docActions"); // NOI18N
        xActionBar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        xActionBar3.setDynamic(true);
        xActionBar3.setPreferredSize(new java.awt.Dimension(91, 30));
        jPanel2.add(xActionBar3, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.gov.etracs.obo.components.ApplicationFeeList applicationFeeList1;
    private com.rameses.gov.etracs.obo.components.ApplicationInfoList applicationInfoList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XActionBar xActionBar3;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XFormPanel xFormPanel2;
    private com.rameses.rcp.control.XLabel xLabel12;
    private com.rameses.rcp.control.XLabel xLabel14;
    private com.rameses.rcp.control.XLabel xLabel15;
    private com.rameses.rcp.control.XLabel xLabel16;
    private com.rameses.rcp.control.XLabel xLabel17;
    private com.rameses.rcp.control.XLabel xLabel18;
    private com.rameses.rcp.control.XLabel xLabel4;
    private com.rameses.rcp.control.XLabel xLabel5;
    private com.rameses.rcp.control.XLabel xLabel7;
    private com.rameses.rcp.control.XLabel xLabel8;
    private com.rameses.rcp.control.XLabel xLabel9;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPanel xPanel2;
    private com.rameses.rcp.control.XTabbedPane xTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
