UPDATE obo_building_application SEt taskid = NULL;
UPDATE obo_building_subapplication SET appid = NULL, taskid = NULL;
DELETE FROM obo_building_application_finding;
DELETE FROM obo_building_application_task;
DELETE FROM obo_building_application_requirement;
DELETE FROM obo_building_subapplication_item;
DELETE FROM obo_building_subapplication_task;
DELETE FROM obo_building_subapplication;
DELETE FROM obo_building_application_info;
DELETE FROM obo_building_application;