/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.components;

import com.rameses.common.PropertyResolver;
import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;

/**
 *
 * @author elmonazareno
 */
@ComponentBean("com.rameses.gov.etracs.obo.components.ProfessionalLookupModel")
public class ProfessionalLookup extends XComponentPanel {

    private String onselect; 
    private String onempty;
    
    private boolean allowCreate;
    private boolean allowOpen;
    
    public String getExpression() {
        return xlookup.getExpression(); 
    }
    public void setExpression( String expression ) {
        xlookup.setExpression( expression ); 
    } 
    
    public String getOnselect() { return onselect; } 
    public void setOnselect( String onselect ) {
        this.onselect = onselect; 
    }
    
    public String getOnempty() { return onempty; } 
    public void setOnempty( String onempty ) {
        this.onempty = onempty; 
    } 
    
    public boolean focusFirstInput() { 
        return xlookup.focusFirstInput(); 
    } 

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        xlookup.setEnabled(enabled);
        btnAdd.setEnabled(enabled);
        com.rameses.rcp.common.ComponentBean bean = (com.rameses.rcp.common.ComponentBean)getComponentBean(); 
        bean.setProperty("allowCreate", enabled);
        bean.setProperty("allowOpen", true);
    }

    @Override
    public void afterLoad() {
        super.afterLoad();
        
        Object caller = getBean();
        Object bean = getComponentBean(); 
        PropertyResolver pr = PropertyResolver.getInstance();
        if ( getOnselect() != null ) {
            Object handler = pr.getProperty(caller, getOnselect()); 
            pr.setProperty(bean, "onselect", handler);
        }
        if ( getOnempty() != null ) {
            Object handler = pr.getProperty(caller, getOnempty()); 
            pr.setProperty(bean, "onempty", handler);
        }
    }

    public String getFontStyle() {
        return xlookup.getFontStyle(); 
    }
    public void setFontStyle( String style ) {
        xlookup.setFontStyle(style); 
    }
    
    /**
     * Creates new form ProfessionalLookup
     */
    public ProfessionalLookup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xlookup = new com.rameses.rcp.control.XLookupField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnView = new com.rameses.rcp.control.XButton();
        btnAdd = new com.rameses.rcp.control.XButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        xlookup.setExpression("#{ (entity.objid !=null) ? entity.lastname + ', ' + entity.firstname + ' ( PRC No: ' + entity.prc?.idno + ') ' : '' }");
        xlookup.setHandler("obo_professional:lookup");
        xlookup.setName("entity"); // NOI18N
        add(xlookup);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 0, 0));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.LINE_AXIS));

        btnView.setDisableWhen("#{allowOpen != true}");
        btnView.setName("viewProfessional"); // NOI18N
        btnView.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 3));
        btnView.setBorderPainted(false);
        btnView.setContentAreaFilled(false);
        btnView.setIconResource("images/toolbars/open.png");
        btnView.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnView.setToolTipText("View Record");
        jPanel4.add(btnView);

        btnAdd.setCaption("");
        btnAdd.setDisableWhen("#{allowCreate != true}");
        btnAdd.setName("addProfessional"); // NOI18N
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setIconResource("images/toolbars/create.png");
        btnAdd.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnAdd.setToolTipText("Add New Record");
        jPanel4.add(btnAdd);

        jPanel2.add(jPanel4);
        jPanel2.add(filler1);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton btnAdd;
    private com.rameses.rcp.control.XButton btnView;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private com.rameses.rcp.control.XLookupField xlookup;
    // End of variables declaration//GEN-END:variables
}
