/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.gov.etracs.obo.building.views;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author elmonazareno
 */
@Template(FormPage.class)
public class BuildingApplicationCapturePage extends javax.swing.JPanel {

    /**
     * Creates new form BuildingApplicationCapturePage
     */
    public BuildingApplicationCapturePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        addressEditor1 = new com.rameses.enterprise.components.AddressEditor();
        entityLookup1 = new com.rameses.entity.components.EntityLookup();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField3 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField4 = new com.rameses.rcp.control.XDecimalField();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xDateField2 = new com.rameses.rcp.control.XDateField();
        xLookupField1 = new com.rameses.rcp.control.XLookupField();
        xLabel3 = new com.rameses.rcp.control.XLabel();
        xLabel21 = new com.rameses.rcp.control.XLabel();

        xFormPanel1.setCaptionWidth(190);

        xTextField1.setCaption("Project Title");
        xTextField1.setName("entity.title"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField1);

        xTextField2.setCaption("Project Description");
        xTextField2.setName("entity.description"); // NOI18N
        xTextField2.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xTextField2);

        addressEditor1.setCaption("Location");
        addressEditor1.setName("entity.location"); // NOI18N
        addressEditor1.setPreferredSize(new java.awt.Dimension(0, 53));
        xFormPanel1.add(addressEditor1);

        entityLookup1.setCaption("Applicant");
        entityLookup1.setName("entity.applicant"); // NOI18N
        entityLookup1.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(entityLookup1);

        xIntegerField1.setCaption("No. of Units");
        xIntegerField1.setName("entity.numunits"); // NOI18N
        xIntegerField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xFormPanel1.add(xIntegerField1);

        xIntegerField2.setCaption("No. of Floors");
        xIntegerField2.setName("entity.numfloors"); // NOI18N
        xFormPanel1.add(xIntegerField2);

        xDecimalField1.setCaption("Total Floor Area");
        xDecimalField1.setName("entity.totalfloorarea"); // NOI18N
        xFormPanel1.add(xDecimalField1);

        xDecimalField2.setCaption("Bldg Height");
        xDecimalField2.setName("entity.height"); // NOI18N
        xFormPanel1.add(xDecimalField2);

        xDecimalField3.setCaption("Project Cost");
        xDecimalField3.setName("entity.projectcost"); // NOI18N
        xDecimalField3.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xDecimalField3.setPreferredSize(new java.awt.Dimension(180, 20));
        xFormPanel1.add(xDecimalField3);

        xDecimalField4.setCaption("Fixed Unit Cost (computed)");
        xDecimalField4.setDisableWhen("#{ true }");
        xDecimalField4.setName("entity.fixedcost"); // NOI18N
        xDecimalField4.setPreferredSize(new java.awt.Dimension(180, 20));
        xFormPanel1.add(xDecimalField4);

        xDateField1.setCaption("Proposed cons. Date");
        xDateField1.setName("entity.dtproposedconstruction"); // NOI18N
        xDateField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xDateField1.setPreferredSize(new java.awt.Dimension(180, 20));
        xFormPanel1.add(xDateField1);

        xDateField2.setCaption("Est. Completion Date");
        xDateField2.setName("entity.dtexpectedcompletion"); // NOI18N
        xDateField2.setPreferredSize(new java.awt.Dimension(180, 20));
        xFormPanel1.add(xDateField2);

        xLookupField1.setCaption("Occupancy Type");
        xLookupField1.setExpression("#{ entity.occupancytype.title }");
        xLookupField1.setHandler("vw_obo_occupancy_type:lookup");
        xLookupField1.setName("entity.occupancytype"); // NOI18N
        xLookupField1.setCellPadding(new java.awt.Insets(20, 0, 0, 0));
        xLookupField1.setPreferredSize(new java.awt.Dimension(0, 20));
        xLookupField1.setToolTipText("");
        xFormPanel1.add(xLookupField1);

        xLabel3.setCaption("Division");
        xLabel3.setDepends(new String[] {"entity.occupancytype"});
        xLabel3.setExpression("#{entity.occupancytype.division.objid}");
        xLabel3.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel3);

        xLabel21.setCaption("Group");
        xLabel21.setDepends(new String[] {"entity.occupancytype"});
        xLabel21.setExpression("#{entity.occupancytype.group.objid}");
        xLabel21.setPreferredSize(new java.awt.Dimension(0, 20));
        xFormPanel1.add(xLabel21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(xFormPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.enterprise.components.AddressEditor addressEditor1;
    private com.rameses.entity.components.EntityLookup entityLookup1;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XDecimalField xDecimalField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField4;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel21;
    private com.rameses.rcp.control.XLabel xLabel3;
    private com.rameses.rcp.control.XLookupField xLookupField1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
